using FeatureRequestPortal.EntityFrameworkCore;
using Xunit;

namespace FeatureRequestPortal.EntityFrameworkCore;

public class FeatureRequestPortalEntityFrameworkCoreCollectionFixtureBase : ICollectionFixture<FeatureRequestPortalEntityFrameworkCoreFixture>
{

}
